name: Update README with Default Branch

on:
  push:
    branches:
      - '**'  # Run on all branch pushes
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Get default branch
        id: default-branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV
          echo "Default branch is $DEFAULT_BRANCH"

      - name: Update README
        run: |
          # Check if we're on the default branch
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          echo "Current branch is $CURRENT_BRANCH"
          
          if [ "$CURRENT_BRANCH" = "$DEFAULT_BRANCH" ]; then
            echo "Updating README.md with default branch information"
            
            # Create backup of README
            cp README.md README.md.bak
            
            # Update version management section in README
            sed -i "/## 버전 관리/,/## /c\## 버전 관리\n\n현재 기본 브랜치: \`$DEFAULT_BRANCH\`\n\n다음 버전 정보를 확인하세요:\n\n- [$DEFAULT_BRANCH](https://github.com/mellerikat/alo/tree/$DEFAULT_BRANCH)\n\n## " README.md || true
            
            # If README doesn't have a version management section, add it
            if ! grep -q "## 버전 관리" README.md; then
              echo -e "\n## 버전 관리\n\n현재 기본 브랜치: \`$DEFAULT_BRANCH\`\n\n다음 버전 정보를 확인하세요:\n\n- [$DEFAULT_BRANCH](https://github.com/mellerikat/alo/tree/$DEFAULT_BRANCH)\n" >> README.md
            fi
            
            # Check if README was changed
            if ! diff -q README.md README.md.bak > /dev/null; then
              git config --global user.name "GitHub Action"
              git config --global user.email "action@github.com"
              git add README.md
              git commit -m "자동 업데이트: README에 기본 브랜치 정보 반영"
              git push
            else
              echo "No changes needed to README"
            fi
          else
            echo "Not on default branch ($DEFAULT_BRANCH), skipping README update"
          fi
